// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTracker_aspNetCoreWebApp_MVC.Data;

namespace MovieTracker_aspNetCoreWebApp_MVC.Migrations
{
    [DbContext(typeof(MovieTracker_aspNetCoreWebApp_MVCContext))]
    [Migration("20220202005102_release_year")]
    partial class release_year
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieTracker_aspNetCoreWebApp_MVC.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateSeen = new DateTime(2021, 10, 24, 19, 51, 2, 411, DateTimeKind.Local).AddTicks(6790),
                            Genre = "fi",
                            Rating = 6,
                            Title = "Interstella"
                        },
                        new
                        {
                            Id = 2,
                            DateSeen = new DateTime(2021, 12, 13, 19, 51, 2, 414, DateTimeKind.Local).AddTicks(4090),
                            Rating = 8,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "action",
                            Title = "The dark knight"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
